language: nodejs

before_script:
- cd client/
- npm install npm -g
- npm cache verify
- npm update
- npm install
- npm run build
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install

script:
- npm run test:coverage
- npm run build
- codecov
- "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
