language: node_js

before_script:
- npm install -g @angular/cli
- cd client/
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run test:coverage
- npm run build
- codecov
- "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
