language: nodejs

addons:
  chrome: stable

before_script:
- npm install -g @angular/cli
- cd client/
- npm install npm -g
- npm install -g codecov
- npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run build
- ng test --watch=false --code-coverage
- codecov
- "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"