language: nodejs

before_script:
- cd client/
- npm install npm -g
- npm install -g codecov
- npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run test:coverage
- npm run build
- codecov
- "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
